<a href="https://colab.research.google.com/github/don1504/don/blob/main/0702_python_numpy_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

배열 생성 및 기본 연산

In [1]:
import numpy as np

# 1D 배열 생성
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print("a + b =", a + b)  # 요소별 덧셈
print("a * b =", a * b)  # 요소별 곱셈
print("a의 평균 =", np.mean(a))


a + b = [5 7 9]
a * b = [ 4 10 18]
a의 평균 = 2.0


2차원 배열 및 슬라이싱

In [2]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

print("전체 배열:\n", arr)
print("첫 번째 행:", arr[0])
print("두 번째 열:", arr[:, 1])  # 모든 행의 두 번째 열만 출력


전체 배열:
 [[1 2 3]
 [4 5 6]]
첫 번째 행: [1 2 3]
두 번째 열: [2 5]


배열 생성 함수

In [3]:
import numpy as np

a = np.arange(0, 10, 2)  # 0부터 10 전까지, 2 간격
b = np.zeros((2, 3))     # 2x3 영행렬
c = np.ones((3, 3))      # 3x3 1행렬

print("arange:", a)
print("zeros:\n", b)
print("ones:\n", c)


arange: [0 2 4 6 8]
zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]
ones:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


배열 형태 변경 및 전치

In [4]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])
reshaped = arr.reshape(2, 3)  # 2행 3열로 변환
transposed = reshaped.T      # 전치 (행/열 바꾸기)

print("Reshaped:\n", reshaped)
print("Transposed:\n", transposed)


Reshaped:
 [[1 2 3]
 [4 5 6]]
Transposed:
 [[1 4]
 [2 5]
 [3 6]]


조건 필터링

In [5]:
import numpy as np

data = np.array([5, 12, 7, 20, 3])
filtered = data[data > 10]  # 10보다 큰 값만 추출

print("원본:", data)
print("10보다 큰 값들:", filtered)


원본: [ 5 12  7 20  3]
10보다 큰 값들: [12 20]


거리 계산

In [6]:
import numpy as np

car_pos = np.array([3, 0])
obstacle_pos = np.array([3, 3])

distance = np.linalg.norm(car_pos - obstacle_pos)
print("장애물까지 거리:", distance)


장애물까지 거리: 3.0


다수 장애물 거리 계산 및 필터링

In [7]:
import numpy as np

car_pos = np.array([3, 0])
obstacles = np.array([[3, 2], [2, 4], [5, 5], [3, 3]])

distances = np.linalg.norm(obstacles - car_pos, axis=1)
print("모든 장애물 거리:", distances)

nearby = obstacles[distances < 3.0]
print("3미터 이내 장애물:", nearby)


모든 장애물 거리: [2.         4.12310563 5.38516481 3.        ]
3미터 이내 장애물: [[3 2]]


경로 예측용 좌표 배열 만들기

In [8]:
import numpy as np

# y축으로 5칸 이동 경로
steps = np.arange(1, 6)
path = np.column_stack((np.full(5, 3), steps))

print("예상 경로 좌표:\n", path)


예상 경로 좌표:
 [[3 1]
 [3 2]
 [3 3]
 [3 4]
 [3 5]]


센서 데이터 시뮬레이션

In [9]:
import numpy as np

true_distance = 2.5  # 실제 거리
noise = np.random.normal(0, 0.1, 5)  # 평균 0, 표준편차 0.1인 노이즈 5개
sensor_readings = true_distance + noise

print("센서 감지값들:", sensor_readings)


센서 감지값들: [2.53968407 2.49009662 2.36091611 2.66596048 2.46934134]


맵 격자 (Grid Map) 생성 및 표시

In [10]:
import numpy as np

map_size = (6, 6)
grid = np.zeros(map_size)

# 자동차 위치
grid[3, 0] = 1  # 1: 자동차

# 장애물 표시
obstacles = [(3, 2), (3, 3), (2, 4), (4, 5)]
for x, y in obstacles:
    grid[x, y] = -1  # -1: 장애물

print("격자 맵:\n", grid)


격자 맵:
 [[ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0. -1.  0.]
 [ 1.  0. -1. -1.  0.  0.]
 [ 0.  0.  0.  0.  0. -1.]
 [ 0.  0.  0.  0.  0.  0.]]
