<a href="https://colab.research.google.com/github/don1504/don/blob/main/0702_python_numpy_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

배열 생성 및 기본 연산

In [1]:
import numpy as np

# 1D 배열 생성
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print("a + b =", a + b)  # 요소별 덧셈
print("a * b =", a * b)  # 요소별 곱셈
print("a의 평균 =", np.mean(a))


a + b = [5 7 9]
a * b = [ 4 10 18]
a의 평균 = 2.0


2차원 배열 및 슬라이싱

In [2]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

print("전체 배열:\n", arr)
print("첫 번째 행:", arr[0])
print("두 번째 열:", arr[:, 1])  # 모든 행의 두 번째 열만 출력


전체 배열:
 [[1 2 3]
 [4 5 6]]
첫 번째 행: [1 2 3]
두 번째 열: [2 5]


배열 생성 함수

In [3]:
import numpy as np

a = np.arange(0, 10, 2)  # 0부터 10 전까지, 2 간격
b = np.zeros((2, 3))     # 2x3 영행렬
c = np.ones((3, 3))      # 3x3 1행렬

print("arange:", a)
print("zeros:\n", b)
print("ones:\n", c)


arange: [0 2 4 6 8]
zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]
ones:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


배열 형태 변경 및 전치

In [4]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])
reshaped = arr.reshape(2, 3)  # 2행 3열로 변환
transposed = reshaped.T      # 전치 (행/열 바꾸기)

print("Reshaped:\n", reshaped)
print("Transposed:\n", transposed)


Reshaped:
 [[1 2 3]
 [4 5 6]]
Transposed:
 [[1 4]
 [2 5]
 [3 6]]


조건 필터링

In [5]:
import numpy as np

data = np.array([5, 12, 7, 20, 3])
filtered = data[data > 10]  # 10보다 큰 값만 추출

print("원본:", data)
print("10보다 큰 값들:", filtered)


원본: [ 5 12  7 20  3]
10보다 큰 값들: [12 20]
